---
# =====================================================================
# Playbook: create_mongodb_atls_org.yml
# Description:
#   This playbook provisions a new MongoDB Atlas Organization using the
#   MongoDB Atlas API. It assigns the requesting ACL group as the org
#   owner (instead of the user running the job), retrieves the Org ID,
#   and sends an email notification with Org details.
# Author: DB Engineering Team
# =====================================================================

- name: Create MongoDB Atlas Organization
  hosts: localhost
  gather_facts: no
  vars:
    atlas_api_public_key: "{{ lookup('env', 'ATLAS_PUBLIC_KEY') }}"
    atlas_api_private_key: "{{ lookup('env', 'ATLAS_PRIVATE_KEY') }}"
    atlas_base_url: "https://cloud.mongodb.com/api/atlas/v1.0"
    org_name: "{{ org_name_input }}"
    requester_acl_group: "{{ acl_group_input }}"
    notify_email: "{{ requester_email }}"

  tasks:
    - name: Create Organization in MongoDB Atlas
      uri:
        url: "{{ atlas_base_url }}/orgs"
        method: POST
        user: "{{ atlas_api_public_key }}"
        password: "{{ atlas_api_private_key }}"
        force_basic_auth: yes
        body_format: json
        body:
          name: "{{ org_name }}"
        return_content: yes
        status_code: 201
      register: org_response

    - name: Extract Org ID
      set_fact:
        org_id: "{{ org_response.json.id }}"

    - name: Assign ACL Group as Owner
      uri:
        url: "{{ atlas_base_url }}/orgs/{{ org_id }}/groups"
        method: POST
        user: "{{ atlas_api_public_key }}"
        password: "{{ atlas_api_private_key }}"
        force_basic_auth: yes
        body_format: json
        body:
          groupId: "{{ requester_acl_group }}"
          roleName: "ORG_OWNER"
        status_code: 201

    - name: Send Email Notification
      mail:
        host: "smtp.company.com"
        port: 25
        to: "{{ notify_email }}"
        subject: "MongoDB Atlas Org Created: {{ org_name }}"
        body: |
          Hello Team,

          A new MongoDB Atlas Organization has been created.

          Organization Name : {{ org_name }}
          Organization ID   : {{ org_id }}
          Assigned ACL Group: {{ requester_acl_group }}

          Regards,
          DB Engineering Automation
