---
- name: Download MongoDB repository and install MongoDB
  hosts: mongo
  become: true
  
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      
    - name: Add Mongo repository
      yum_repository:
        name: mongodb-org-4.4
        description: MongoDB Repository Repo
        baseurl: https://repo.mongodb.org/yum/redhat/$...
        gpgkey: https://www.mongodb.org/static/pgp/se...
    
    - name: Install MongoDB
      yum: 
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Enable MongoDB to run on boot
      service: 
        name: mongod 
        enabled: yes
        state: started
...
